export const UniversitiesList = [
    "Harvard University",
    "Stanford University",
    "Massachusetts Institute of Technology (MIT)",
    "California Institute of Technology (Caltech)",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Chicago (Booth)",
    "University of Pennsylvania (Wharton)",
    "Duke University",
    "Northwestern University (Kellogg)",
    "University of California, Berkeley (UC Berkeley)",
    "University of California, Los Angeles (UCLA)",
    "University of Michigan, Ann Arbor",
    "Cornell University",
    "Johns Hopkins University",
    "New York University (NYU)",
    "University of Virginia (Darden)",
    "University of North Carolina at Chapel Hill (Kenan-Flagler)",
    "University of Texas at Austin",
    "Carnegie Mellon University",
    "Emory University (Goizueta)",
    "Georgetown University (McDonough)",
    "Georgia Institute of Technology",
    "University of Southern California (USC)",
    "University of Florida",
    "Boston University",
    "University of Wisconsin-Madison",
    "University of Illinois Urbana-Champaign",
    "University of Washington",
    "University of Notre Dame (Mendoza)",
    "Vanderbilt University (Owen)",
    "Rice University",
    "Brown University",
    "Dartmouth College (Tuck)",
    "Indiana University (Kelley)",
    "Ohio State University (Fisher)",
    "University of Minnesota",
    "University of Maryland, College Park",
    "University of Miami",
    "University of Arizona",
    "University of Colorado Boulder",
    "University of California, San Diego (UCSD)",
    "University of California, Davis (UC Davis)",
    "Rutgers University",
    "Texas A&M University",
    "Brigham Young University (Marriott)",
    "Arizona State University (W.P. Carey)",
    "University of Pittsburgh",
    "University of Rochester (Simon)",
    "University of Georgia (Terry)",
    "University of Toronto",
    "McGill University",
    "University of British Columbia (UBC)",
    "University of Alberta",
    "University of Waterloo",
    "Western University (Ivey)",
    "Queen's University (Smith)",
    "University of Calgary",
    "McMaster University (DeGroote)",
    "Université de Montréal",
    "Dalhousie University",
    "University of Ottawa",
    "Simon Fraser University",
    "York University (Schulich)",
    "Concordia University (John Molson)",
    "University of Saskatchewan",
    "University of Victoria",
    "University of Guelph",
    "Université Laval",
    "Carleton University",
    "University of Oxford",
    "University of Cambridge",
    "London School of Economics and Political Science (LSE)",
    "Imperial College London",
    "INSEAD (France/Singapore)",
    "HEC Paris (France)",
    "IE Business School (Spain)",
    "ESADE Business School (Spain)",
    "ETH Zurich (Switzerland)",
    "University of St. Gallen (Switzerland)",
    "National University of Singapore (NUS)",
    "Tsinghua University"
  ]; 

  export const IndustriesList = [
    "SaaS",
    "FinTech",
    "HealthTech",
    "BioTech",
    "ClimateTech",
    "EdTech",
    "AgriTech",
    "PropTech",
    "LegalTech",
    "InsurTech",
    "ConsumerTech",
    "DeepTech",
    "AI & Machine Learning",
    "Web3 & Blockchain",
    "E-commerce",
    "Marketplaces",
    "Hardware",
    "Robotics",
    "Cybersecurity",
    "Mobility & Transportation",
    "SpaceTech",
    "Clean Energy",
    "FoodTech",
    "Gaming & eSports",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Mixed Reality (MR)",
    "Media & Entertainment",
    "MarTech (Marketing Tech)",
    "AdTech (Advertising Tech)",
    "FashionTech",
    "SportsTech",
    "Supply Chain & Logistics",
    "Manufacturing & Industrial Tech",
    "Social Platforms",
    "Collaboration & Productivity Tools",
    "Travel & Hospitality",
    "DTC (Direct-to-Consumer)",
    "Consumer Goods",
    "Creator Economy",
    "Sharing Economy",
    "GovTech",
    "RegTech",
    "Construction Tech",
    "Civic Tech",
    "Quantum Computing",
    "Telecommunications",
    "Mobility-as-a-Service",
    "FinOps & Accounting Tech",
    "HR Tech",
    "Wellness & Fitness Tech",
    "MedTech (Medical Devices & Diagnostics)",
    "Longevity & Aging Tech",
    "Circular Economy & Waste Management",
    "WealthTech (Investment & Asset Management Tech)",
    "Smart Cities",
    "Remote Work & Hybrid Tech",
    "Business Intelligence & Analytics",
    "SalesTech",
    "Streaming & Content Platforms",
    "Music Tech",
    "Ethical AI & Privacy Tech",
    "Mental Health & NeuroTech",
    "Psychedelics & Alternative Medicine",
    "Open Source & Developer Tools",
  ];
  
